name: Lambda Deployments

on:
  push:
    branches:
    - main
# commit
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.13

    - name: zip Lambda Function
      run: |
          zip -r9 lambda.zip lambdaFunction.py
    - name: AWS Deploy
      run: |
          aws lambda update-function-code --function-name NameOfLambdaFunction --zip-file fileb://lambda.zip

    
