name: Lambda Deployments

on:
  push:
    branches:
    - main
# commit
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.13

    - name: zip Lambda Function
      run: |
          npm run build:lambda ;  cd dist/apps/lambda/; aws lambda update-function-code --function-name my-function --zip-file fileb://function.zip

          
    # - name: AWS Deploy
    #   run: |
         
    # - name: Switch to frontend dir
    #   run: cd apps/frontend
      
    # - name: Install dependencies
    #   run: npm i nx -g; npm install; npx nx build minidollop-ui;
    #   # run: cd apps/frontend;npm install;npm run build:prod

    # # - name: Run tests
    # #   run: npm run test:headless

    # # - name: Build
    # #   run: npm run build:prod

    # - name: Deploy
    #   if: success()
    #   run: aws s3 sync ./dist/apps/minidollop-ui/ s3://s3-for-beanie
    #       ls; zip -r9 lambda.zip lambdaFunction.py
    # - name: AWS Deploy
    #   run: |
    #       aws lambda update-function-code --function-name NameOfLambdaFunction --zip-file fileb://lambda.zip

    
